// booth-react/src/Components/Room/RoomComponent.tsx
import React, { useEffect, useState } from 'react'
import { BoothApi } from '../../Services/Booth-Api'
import { Subscription } from 'rxjs';
import { RoomUpdatedModel } from '../../Models/ws-models';
import { RoomModel } from '../../Models/room-model';
import { Button, List, ListItem, ListItemText, Typography } from '@mui/material';
import Moment from 'moment';

import './RoomComponent.scss';
import { MessageModel } from '../../Models/message-model';
import { MessageInputComponent } from '../MessageInput/MessageInputComponent';

export const RoomComponent = () => {

  const api = BoothApi.instance;
  const [currentRoom, setCurrentRoom] = useState<RoomModel | undefined>(undefined);

  useEffect(() => {
    const subscriptions = new Subscription();

    subscriptions.add(api.wssInstance.newMessage.subscribe({
      next: (room: RoomUpdatedModel) => {
        if (!currentRoom) {
          // hydrate.
          setCurrentRoom(room);
          return;
        } else {
          // update.
          const clonedObj = {...currentRoom};
          clonedObj.title = room.title;
          clonedObj.description = room.description;
          clonedObj.messages = room.messages;
        
          setCurrentRoom(clonedObj);
        }
      }
    }));

    return (() => {
      subscriptions.unsubscribe();
    })
  }, [currentRoom]);

  const exitRoom = async () => {
    if (!currentRoom) return;
    try {
      const resp = await api.exitRoom(currentRoom.id)
      setCurrentRoom(undefined);
    } catch (err) {
      if (err instanceof Error) {
        console.log(err.message);
      }
    }
  }

  const handleNewMessage = async (msg: string) => {
    if (!currentRoom) return;

    try {
      api.sendMessage({
        roomId: currentRoom.id,
        message: msg
      });
    } catch (err) {
      console.log(err);
    }
  }

  return (
    <div className='div-room-container'>
      <div className='div-room-container__header'>
        {currentRoom && <Button variant="outlined" onClick={exitRoom}>Exit</Button>}
        {currentRoom ? currentRoom.title : 'none'}
        {<MessageInputComponent onNewMessage={handleNewMessage}></MessageInputComponent>}
      </div>
      {currentRoom &&
        <div className='div-room-container__chat'>
          <List sx={{ width: '100%', overflow: 'auto', bgcolor: 'background.paper' }}>

            {currentRoom.messages.map((msg: MessageModel) => (
              <ListItem alignItems='flex-start'>
                <ListItemText key={msg.id}
                  primary={`${msg.owner.username} - ${Moment(msg.timestamp).format('lll')}`}
                  secondary={
                    <React.Fragment>
                      <Typography
                        sx={{ display: 'inline' }}
                        component="span"
                        variant='body2'
                        color="text.primary"
                      >
                      </Typography>
                      {`${msg.message}`}
                    </React.Fragment>
                  }
                />

              </ListItem>
            ))}
          </List>
        </div>
      }
    </div>
  )
}

// booth-ng/src/app/components/room/room.component.ts
import { HttpErrorResponse } from '@angular/common/http';
import { Component, OnDestroy, OnInit } from '@angular/core';
import { FormBuilder, FormGroup } from '@angular/forms';
import { Subscription, } from 'rxjs';
import { MessageModel } from 'src/app/models/message-model';
import { RoomModel } from 'src/app/models/room-model';
import { RoomUpdatedModel } from 'src/app/models/ws-models';
import { BoothApiService } from 'src/app/services/booth-api.service';

@Component({
  selector: 'app-room',
  templateUrl: './room.component.html',
  styleUrls: ['./room.component.scss']
})
export class RoomComponent implements OnInit, OnDestroy {

  private subscriptions = new Subscription();

  public currentRoom: RoomModel | undefined;

  public roomTitle: string = '';
  public roomDescription: string = '';
  public messages: string[] = [];

  public errorMessage = '';
  public newMessage = '';

  constructor(private api: BoothApiService, private fb: FormBuilder) { }

  ngOnInit(): void {
    this.subscriptions.add(this.api.wss.newMessage.subscribe((room: RoomUpdatedModel) => {
      if (!this.currentRoom) {
        this.currentRoom = {...room}
        return;
      }
      this.currentRoom.title = room.title;
      this.currentRoom.description = room.description;
      this.currentRoom.users = [...room.users];
      this.currentRoom.messages = [...room.messages];
    }));
  }

  ngOnDestroy(): void {
    this.subscriptions.unsubscribe();
  }

  public doExitRoom() {
    if (!this.currentRoom || !this.currentRoom.id) {
      console.log('### doExitRoom failed');
      return;
    }

    this.api.exitRoom(this.currentRoom.id).subscribe(
      {
        next: () => {
          console.log('### exited room');
          this.currentRoom = undefined;
        },
        error: (err: HttpErrorResponse) => {
          console.log('### doExitRoom failed', `${err.status}. ${err.statusText}`);
        }
      }
    );
  }

  public sendMessage(): void {
    if (!this.currentRoom || !this.currentRoom.id) {
      console.log('fail to send');
      return;
    }

    this.api.sendMessage({ roomId: this.currentRoom?.id, message: this.newMessage }).subscribe(
      {
        next: (resp: MessageModel) => { },
        error: (err: HttpErrorResponse) => {
          console.log('### sendMessage failed', `${err.status}. ${err.statusText}`);
        }
      }
    );
    this.newMessage = '';
  }
}

<div class="div-room-container">
    <ng-container *ngIf="currentRoom; then loggedIn; else loggedOut">
    </ng-container>

    <ng-template #loggedIn>
        <div class='div-header'>
            <div>{{currentRoom?.title}}</div>
            <div>{{currentRoom?.description}}</div>
            <span *ngFor="let user of currentRoom?.users">{{user.username}}</span>
            <button mat-icon-button (click)="doExitRoom()"><mat-icon>delete</mat-icon></button>
        </div>
    </ng-template>

    <ng-template #loggedOut>
        <div class="div-header">
            Empty Room
        </div>
    </ng-template>

    <div class='div-messages'>
        <div *ngFor="let msg of currentRoom?.messages">
            <div>{{msg.timestamp}} {{msg.owner.username}} {{msg.message}}</div>
        </div>
    </div>
    <div class="div-send-message">
        <mat-form-field>
            <mat-label>New Message</mat-label>
            <input matInput [(ngModel)]="newMessage">
            <button mat-icon-button matSuffix (click)="sendMessage()" [attr.aria-label]="'send mesage'">
                <mat-icon>send</mat-icon>
            </button>
        </mat-form-field>
    </div>
</div>
