// booth-ng/src/app/components/rooms/rooms.component.ts
import { HttpErrorResponse } from '@angular/common/http';
import { Component, OnDestroy } from '@angular/core';
import { MatTableDataSource } from '@angular/material/table';
import { Subscription, filter, map } from 'rxjs';
import { RoomModel } from 'src/app/models/room-model';
import { RoomChangedModel, RoomUpdatedModel } from 'src/app/models/ws-models';
import { BoothApiService } from 'src/app/services/booth-api.service';

export interface PeriodicElement {
  id: string;
  title: string;
  description: string;
  owner: string;
  numOfUsers: number;
}

@Component({
  selector: 'app-rooms',
  templateUrl: './rooms.component.html',
  styleUrls: ['./rooms.component.scss']
})
export class RoomsComponent implements OnDestroy {
  private subscriptions = new Subscription();
  columnHeaders: string[] = ['title', 'description', 'owner', 'nUsers', 'delete', 'join'];

  dataSource: MatTableDataSource<PeriodicElement> = new MatTableDataSource();

  message: string = '';
  rooms: RoomModel[] = [];

  constructor(private api: BoothApiService) {

    this.subscriptions.add(
      this.api.wss.roomAdded.subscribe(
        {
          next: (resp: RoomChangedModel) => {
            if (this.rooms.length === 0) {
              this.rooms = [...this.rooms, ...resp.rooms];
            } else {
              this.rooms.push(resp.room);
            }

            this.updateTable();
          },
          error: (err: HttpErrorResponse) => { }
        }
      )
    )

    this.subscriptions.add(
      this.api.wss.roomDeleted.subscribe(
        {
          next: (resp: RoomChangedModel) => {
            const idx = this.rooms.findIndex(r => r.id === resp.room.id);
            if (idx >= 0) {
              this.rooms.splice(idx, 1);
            }

            this.updateTable();
          },
          error: (err: HttpErrorResponse) => { }
        }
      )
    )

    this.subscriptions.add(
      this.api.wss.roomUpdated.subscribe(
        {
          next: (resp: RoomUpdatedModel) => {
            const room = this.rooms.find(r => r.id === resp.id);
            if (room) {
              room.users.length = 0;
              room.users = [...resp.users];
              room.title = resp.title;
              room.description = resp.description;
            }

            this.updateTable();
          },
          error: (err: HttpErrorResponse) => { }
        }
      )
    )
  }

  ngOnDestroy(): void {
    this.subscriptions.unsubscribe();
  }

  public getAllRooms(): void {
    this.api.getAllRooms().subscribe(
      {
        next: (rooms: RoomModel[]) => {
          this.rooms = [...rooms];
          this.updateTable();
          this.message = '';
        },
        error: (err: HttpErrorResponse) => {
          this.message = `${err.status}. ${err.statusText}`;
        }
      }
    )
  }

  public deleteRoom(roomId: string | undefined) {
    if (!roomId) return;
    this.api.deleteRoom(roomId).subscribe(
      {
        next: (room: RoomModel) => {
        },
        error: (err: HttpErrorResponse) => {
          this.message = `${err.status}. ${err.statusText}`;
        }
      }
    );
  }

  public joinRoom(roomId: string | undefined) {
    if (!roomId) return;
    this.api.joinRoom(roomId).subscribe({
      next: (room: RoomModel) => {
        console.log('### joinRoom', room)
      },
      error: (err) => {
        console.log('### joinRoom exception', err.message)
      }
    });
  }

  private updateTable(): void {
    const newData: PeriodicElement[] = [];
    this.dataSource.data = [];
    for (const room of this.rooms) {
      newData.push({
        id: room.id,
        title: room.title,
        description: room.description,
        owner: room.owner.username,
        numOfUsers: room.users.length
      });
    }

    this.dataSource.connect().next(newData);
  }
}

<div class="div-rooms-container">
    <div class="div-rooms-action-row">
        <button mat-icon-button color="primary" (click)="getAllRooms()"><mat-icon>refresh</mat-icon></button>
        <div>{{message}}</div>
    </div>
    <div class="div-rooms">
        <table mat-table [dataSource]="dataSource" class="mat-elevation-z8">
            <!--- Note that these columns can be defined in any order.
              The actual rendered columns are set as a property on the row definition" -->

            <!-- Position Column -->
            <ng-container matColumnDef="title">
                <th mat-header-cell *matHeaderCellDef> Title </th>
                <td mat-cell *matCellDef="let item"> {{item.title}} </td>
            </ng-container>

            <!-- Name Column -->
            <ng-container matColumnDef="description">
                <th mat-header-cell *matHeaderCellDef> Description </th>
                <td mat-cell *matCellDef="let item"> {{item.description}} </td>
            </ng-container>

            <!-- Weight Column -->
            <ng-container matColumnDef="owner">
                <th mat-header-cell *matHeaderCellDef> Owner </th>
                <td mat-cell *matCellDef="let item"> {{item.owner}} </td>
            </ng-container>

            <!-- Symbol Column -->
            <ng-container matColumnDef="nUsers">
                <th mat-header-cell *matHeaderCellDef> # of Users </th>
                <td mat-cell *matCellDef="let item">{{item.numOfUsers}} </td>
            </ng-container>

            <ng-container matColumnDef="delete" stickyEnd>
                <th mat-header-cell *matHeaderCellDef aria-label="delete">&nbsp;</th>
                <td mat-cell *matCellDef="let element">
                    <button mat-icon-button (click)="deleteRoom(element.id)"><mat-icon>delete</mat-icon></button>
                </td>
            </ng-container>

            <ng-container matColumnDef="join" stickyEnd>
                <th mat-header-cell *matHeaderCellDef aria-label="join">&nbsp;</th>
                <td mat-cell *matCellDef="let element">
                    <button mat-icon-button (click)="joinRoom(element.id)"><mat-icon>meeting_room</mat-icon></button>
                </td>
            </ng-container>

            <tr mat-header-row *matHeaderRowDef="columnHeaders"></tr>
            <tr mat-row *matRowDef="let row; columns: columnHeaders;"></tr>
        </table>
    </div>
    <!-- <div class="div-rooms">
        <div *ngFor="let room of rooms">
            <mat-card>
                <mat-card-title>
                    {{room.title}}
                </mat-card-title>
                <mat-card-subtitle>{{room.description}} {{room.users.length}}</mat-card-subtitle>
                <mat-card-actions>
                    <button mat-icon-button (click)="deleteRoom(room.id)"><mat-icon>delete</mat-icon></button>
                    <button mat-icon-button (click)="joinRoom(room.id)"><mat-icon>chat</mat-icon></button>
                </mat-card-actions>
            </mat-card>
        </div>
    </div> -->
</div>

// booth-react/src/Components/Rooms/RoomsComponent.tsx
import './RoomsComponent.scss';
import { Box, Button, IconButton, Paper, Table, TableBody, TableCell, TableContainer, TableHead, TableRow } from "@mui/material";
import { useEffect, useState } from 'react';
import { Chat, DeleteForever } from '@mui/icons-material';
import { BoothApi } from '../../Services/Booth-Api';
import { RoomModel } from "../../Models/room-model";
import { RoomChangedModel, RoomUpdatedModel } from "../../Models/ws-models";
import { Subscription } from "rxjs";


export const RoomsComponent = () => {

  const [message, setMessage] = useState('');
  const [rooms, setRooms] = useState<RoomModel[]>([]);
  const api = BoothApi.instance;

  useEffect(() => {
    console.log('useEffect');
    const subscriptions = new Subscription();

    subscriptions.add(api.wssInstance.roomAdded.subscribe({
      next: (data: RoomChangedModel) => {
        setRooms([...data.rooms]);
      }
    }))

    subscriptions.add(api.wssInstance.roomDeleted.subscribe({
      next: (data: RoomChangedModel) => {
        setRooms([...data.rooms]);
      }
    }))

    subscriptions.add(api.wssInstance.roomUpdated.subscribe({
      next: (data: RoomUpdatedModel) => {
        const clonedArr = [...rooms];

        const room = clonedArr.find(r => r.id === data.id);
        if (room) {
          room.title = room.title;
          room.description = room.description;
          room.users = [...data.users];
        
          setRooms(clonedArr);
        }
      }
    }))

    return () => {
      console.log('useEffect-cleanup');
      subscriptions.unsubscribe();
    }
  }, [rooms]);

  const doRefresh = async () => {
    try {
      const allRooms: RoomModel[] = await api.getAllRooms();
      setRooms([...allRooms])
      setMessage('');
    } catch (err) {
      if (err instanceof Error) {
        setMessage(err.message);
      }
    }
  }

  const deleteRoom = async (roomId: string) => {
    try {
      await api.deleteRoom(roomId);
      setMessage('');
    } catch (err) {
      if (err instanceof Error) {
        setMessage(err.message);
      }
    }
  }

  const joinRoom = async (roomId: string) => {
    try {
      const room: RoomModel = await api.joinRoom(roomId);
      setMessage('');
    } catch (err) {
      if (err instanceof Error) {
        setMessage(err.message);
      }
    }
  }


  return (
    <div className='div-rooms-container'>
      <Box display='flex' padding={1} flexDirection='row' alignItems='center' columnGap={2}>
        <div>Rooms</div>
        <Button onClick={doRefresh} variant="outlined">Refresh</Button>
        <div>{message}</div>
      </Box>
      <div className='table-container'>
        <TableContainer component={Paper}>
          <Table sx={{ minWidth: 300 }} stickyHeader size='small' aria-label='a dense table'>
            <TableHead>
              <TableRow>
                <TableCell align='left' style={{ width: 'auto' }}>Title</TableCell>
                <TableCell align='right' style={{ width: 'auto' }}>Description</TableCell>
                <TableCell align='right' style={{ width: 'auto' }}>Owner</TableCell>
                <TableCell align='right' style={{ width: 'auto' }}>nUsers</TableCell>
                <TableCell align='right' style={{ width: 'auto' }}></TableCell>
              </TableRow>
            </TableHead>
            <TableBody>
              {rooms.map((row: RoomModel) => (
                <TableRow key={row.id} sx={{ '&:last-child td, &:last-child th': { border: 0 } }}>
                  <TableCell align='left'>{row.title}</TableCell>
                  <TableCell align='right'>{row.description}</TableCell>
                  <TableCell align='right'>{row.owner.username}</TableCell>
                  <TableCell align='right'>{row.users.length}</TableCell>
                  <TableCell align='right'>
                    <IconButton onClick={() => joinRoom(row.id)} size="large">
                      <Chat />
                    </IconButton>
                    <IconButton onClick={() => deleteRoom(row.id)} size='large'>
                      <DeleteForever />
                    </IconButton>
                  </TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
        </TableContainer>
      </div>
    </div>
  )
}
